[project]
name = "cnb_2as"
authors = [
    { name = "CT Group", email = "dev@ctgroup.vn" },
]
description = "AI Đánh Giá Nhân Sự – Thử Việc & Tái Ký Hợp Đồng"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

dependencies = [
    "reportlab"
]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0"

[tool.ct_template]
prefix           = "CNB"
module           = "cnb_2as"
app_name         = "cnb_2as"
app_slug         = "2as-employee-assessment"
get_context_file = "cnb_2as/api.py"
context_url      = "/api/method/cnb_2as.api.get_context"
frontend_src     = "frontend/"
